// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/141yuya/go-clean-architecture/domain/repositories"
	"github.com/141yuya/go-clean-architecture/infrastructure"
	"github.com/141yuya/go-clean-architecture/interfaces/controllers"
	"github.com/141yuya/go-clean-architecture/interfaces/gateways"
	"github.com/141yuya/go-clean-architecture/usecases"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitUserController(handler *infrastructure.SqlHandler) controllers.UserController {
	userRepository := gateways.NewUserRepository(handler)
	userUsecase := usecases.NewUserUsecase(userRepository)
	userController := controllers.NewUserController(userUsecase)
	return userController
}

// wire.go:

var superSet = wire.NewSet(gateways.NewUserRepository, wire.Bind(new(repositories.UserRepository), new(*gateways.UserRepository)), usecases.NewUserUsecase, controllers.NewUserController)
